-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.pato
(
    id uuid NOT NULL,
    fk_mae_id uuid NOT NULL,
    nome character varying NOT NULL,
    valor double precision NOT NULL,
    vendido boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id uuid NOT NULL,
    nome character varying NOT NULL,
    desconto boolean DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venda_pato_cliente
(
    id uuid NOT NULL,
    fk_cliente_id uuid NOT NULL,
    fk_pato_id uuid NOT NULL,
    valor double precision NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.pato
    ADD CONSTRAINT fk_mae_id FOREIGN KEY (fk_mae_id)
    REFERENCES public.pato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.venda_pato_cliente
    ADD CONSTRAINT fk_cliente_id FOREIGN KEY (fk_cliente_id)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.venda_pato_cliente
    ADD CONSTRAINT fk_pato_id FOREIGN KEY (fk_pato_id)
    REFERENCES public.pato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;